title: Dr. Tim Schürmann
logo: "/images/profile_image_circular.jpg?raw=true"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Senior Data Scientist with a background in psychology
  <br><br>
  This portfolio showcases a selection of projects I have engaged in privately or professionally. In the latter case, projects have been rebuilt to omit sensitive information.
  <br><br>
  <a href="linkedin.com/in/tim-schürmann-865731ab">View my LinkedIn Profile</a><br>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-XP9NB3LKSY
